server:
  port: 8085

size: 176cm

age: 20

content: hight ${size}, age:${age}

WeChat:
  appId: wxe4e260d56bbd711b
  appSecret: c49f94a1bbfbeca3f02f643f971b7df2
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  authUrl: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE#wechat_redirect
  callBackUrl: http://18s935291p.51mypc.cn/wechat/authCallBack
  authTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
  refreshTokenUrl: https://api.weixin.qq.com/sns/oauth2/refresh_token?appid=APPID&grant_type=refresh_token&refresh_token=REFRESH_TOKEN
  userInforUrl: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN

User:
  age: 19
  name: Jack-AAA
  address: shanghai

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_demo?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    suffix: .html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates/
    order: 1
    settings: 
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true


